### ISSUE TITLE
Error with adaptor_name

### ISSUE THREAD

**Issue by bruli** [rezzza/rest-api-behat-extension#31]
Error
```bash
 [Symfony\Component\DependencyInjection\Exception\ParameterNotFoundException]                          
  The service "rezzza.json_api.rest.rest_api_browser" has a dependency on a non-existent parameter "re  
  zzza.json_api.rest.adaptor_name". Did you mean this: "rezzza.json_api.rest.base_url"? 
```

My behat.yml:
```yml
default:
    extensions:
        Behat\Symfony2Extension:  ~
        Rezzza\RestApiBehatExtension\Extension:
            rest:
                base_url: http://localhost:80/app_test.php/api
                store_response: true
                adaptor_name: curl
```

**Comment by tyx** [comment]
Hi,

Looks weird !

Can you have a look on this line https://github.com/rezzza/rest-api-behat-extension/blob/b6de2c00953a8947230f43a8fabb8f9d57789ac2/src/Extension.php#L18 and dump the config you have ?

**Comment by bruli** [comment]
My behat.yml is in my previous message.

**Comment by tyx** [comment]
Sure, but as it looks correct, we need to find why you have this message. Dumping the `$config` would be helpful.

**Comment by bruli** [comment]
```php
array(1) {
  'rest' =>
  array(3) {
    'base_url' =>
    string(36) "http://localhost:80/app_test.php/api"
    'store_response' =>
    bool(true)
    'adaptor_name' =>
    string(4) "curl"
  }
}
```

**Comment by tyx** [comment]
Thanks. So no idea why you have this error. If you able to help by debugging yourself, please do. 

Otherwise you can hardcoded your value here waiting for a better solution : https://github.com/rezzza/rest-api-behat-extension/blob/master/src/Resources/services.xml#L23

**Comment by stephpy** [comment]
Hi,

Did you re-define a `rezzza.json_api.rest.rest_api_browser` definition in your bundles ?

What is weird too is than `rezzza.json_api.rest.adaptor_name` is cut with spaces, it should not be the case, even with line break.

**Comment by bruli** [comment]
This is my behat.yml

```yml
default:
    extensions:
        Behat\Symfony2Extension:  ~
        Rezzza\RestApiBehatExtension\Extension:
            rest:
                base_url: http://localhost:80/app_test.php/api
                store_response: true
                adaptor_name: curl
    suites:
        default:
            bundle: CoreApiBundle
            type: symfony_bundle
            paths:
                - %paths.base%/features
            filters:
                tags: ~@ignore
            contexts:
                - Rezzza\RestApiBehatExtension\RestApiContext
                - Rezzza\RestApiBehatExtension\Json\JsonContext:
                    jsonSchemaBaseUrl: %paths.base%/features/bootstrap/schemas
                - Core\Behat\Infrastructure\Context\CoreApiContext
                - Core\Behat\Infrastructure\Context\CoreFeatureContext:
                    environmentArranger: @environment.arranger
                - Core\Behat\Infrastructure\Context\EntityContext
                - Core\Behat\Infrastructure\Context\SolrContext
                - Core\Behat\Infrastructure\Context\ParseContext:
                    testUserName: letgoTestUser
                    testUserPassword: letgoTestUserPass
                    testUserEmail: letgotestuser@letgotest.com
                - Core\Behat\Infrastructure\Context\ChatContext:
                    restApiBrowser: @rezzza.json_api.rest.rest_api_browser
                    entityManagerChat: @doctrine.orm.chat_entity_manager
                - Core\Behat\Infrastructure\Context\ConversationContext:
                    conversationRepository: @conversation.chat.repository
                    restApiBrowser: @rezzza.json_api.rest.rest_api_browser
                    entityManagerChat: @doctrine.orm.chat_entity_manager
                - Core\Behat\Infrastructure\Context\ProductContext:
                    productRepository: @product.repository
                - Core\Behat\Infrastructure\Context\UserContext:
                    userRepository: @user.repository
                    userMuteRepository: @ambatana.user.infrastructure.user_mute_repository
                    entityManagerOperational: @doctrine.orm.entity_manager
```

in rezzza/rest-api-behat-extension/src/Resources/services.xml:
```xml
...
<service id="rezzza.json_api.rest.rest_api_browser" class="Rezzza\RestApiBehatExtension\Rest\RestApiBrowser" public="false">
            <argument>%rezzza.json_api.rest.base_url%</argument>
            <argument>%rezzza.json_api.rest.adaptor_name%</argument>
        </service>
...
```

I replace %rezza.json_api.rest.adaptor_name% by 'curl', and works fine.
